import type { AppModuleDefinition, CalibrationStatus, ContractStatus, ContractType, EntityConfig, InventoryStatus, ModuleId, RoleAccessConfig, SelectOption, ServiceOrderStatus, BudgetStatus, EquipmentStatus } from './types.js'

export const EQUIPMENT_STATUS_OPTIONS: SelectOption[] = [
  { label: 'Em Operação', value: 'Em Operação' },
  { label: 'Em Manutenção', value: 'Em Manutenção' },
  { label: 'Aguardando Peça', value: 'Aguardando Peça' },
  { label: 'Fora de Uso', value: 'Fora de Uso' },
]

export const INVENTORY_STATUS_OPTIONS: SelectOption[] = [
  { label: 'Ativo', value: 'Ativo' },
  { label: 'Inativo', value: 'Inativo' },
]

export const BUDGET_STATUS_OPTIONS: SelectOption[] = [
  { label: 'Em elaboração', value: 'Em elaboração' },
  { label: 'Enviado', value: 'Enviado' },
  { label: 'Aprovado', value: 'Aprovado' },
  { label: 'Rejeitado', value: 'Rejeitado' },
  { label: 'Faturado', value: 'Faturado' },
]

export const CONTRACT_STATUS_OPTIONS: SelectOption[] = [
  { label: 'Ativo', value: 'Ativo' },
  { label: 'Pendente', value: 'Pendente' },
  { label: 'Suspenso', value: 'Suspenso' },
  { label: 'Encerrado', value: 'Encerrado' },
]

export const CONTRACT_TYPE_OPTIONS: SelectOption[] = [
  { label: 'Manutenção', value: 'Manutenção' },
  { label: 'Locação', value: 'Locação' },
  { label: 'Suporte', value: 'Suporte' },
  { label: 'Assistência Técnica', value: 'Assistência Técnica' },
  { label: 'Outro', value: 'Outro' },
]

export const SERVICE_ORDER_STATUS_OPTIONS: SelectOption[] = [
  { label: 'Aguardando Início', value: 'Aguardando Início' },
  { label: 'Em Manutenção', value: 'Em Manutenção' },
  { label: 'Aguardando Peça', value: 'Aguardando Peça' },
  { label: 'Aguardando Cliente', value: 'Aguardando Cliente' },
  { label: 'Em Teste', value: 'Em Teste' },
  { label: 'Pronto para Retirada', value: 'Pronto para Retirada' },
  { label: 'Concluída', value: 'Concluída' },
]

export const PRIORITY_OPTIONS: SelectOption[] = [
  { label: 'Baixa', value: 'Baixa' },
  { label: 'Media', value: 'Media' },
  { label: 'Alta', value: 'Alta' },
  { label: 'Critica', value: 'Critica' },
]

export const CALIBRATION_STATUS_OPTIONS: SelectOption[] = [
  { label: 'Válido', value: 'Válido' },
  { label: 'Vencendo', value: 'Vencendo' },
  { label: 'Vencido', value: 'Vencido' },
]

export const MODULE_IDS: ModuleId[] = [
  'dashboard',
  'financeiro',
  'ordens-servico',
  'historico-os',
  'equipamentos',
  'orcamentos',
  'funcionarios',
  'clientes',
  'contratos',
  'certificados',
  'fornecedores',
  'pecas',
  'acessorios',
  'padroes-calibracao',
  'usuarios',
  'configuracoes',
]

export const DEFAULT_ROLE_ACCESS: RoleAccessConfig = {
  admin: [...MODULE_IDS],
  gerente: MODULE_IDS.filter((id) => id !== 'usuarios'),
  tecnico: [
    'dashboard',
    'ordens-servico',
    'historico-os',
    'equipamentos',
    'clientes',
    'certificados',
    'pecas',
    'acessorios',
    'padroes-calibracao',
  ],
  operador: [
    'dashboard',
    'ordens-servico',
    'equipamentos',
    'orcamentos',
    'clientes',
    'contratos',
  ],
}

export const APP_MODULES: AppModuleDefinition[] = [
  {
    id: 'dashboard',
    label: 'Visão Geral',
    shortLabel: 'Painel',
    kind: 'dashboard',
    description: 'Resumo operacional, carteira técnica e indicadores do dia.',
  },
  {
    id: 'financeiro',
    label: 'Painel Financeiro',
    shortLabel: 'Financeiro',
    kind: 'finance',
    description: 'Receita projetada, contratos, propostas e serviços.',
  },
  {
    id: 'ordens-servico',
    label: 'Ordens de Serviço',
    shortLabel: 'Ordens',
    kind: 'service-orders',
    description: 'Abertura, acompanhamento e encerramento técnico.',
    collection: 'ordensServico',
  },
  {
    id: 'historico-os',
    label: 'Histórico Técnico',
    shortLabel: 'Histórico',
    kind: 'history',
    description: 'Consulta rápida do acervo de ordens já concluídas.',
    collection: 'historicoOS',
  },
  {
    id: 'equipamentos',
    label: 'Equipamentos',
    shortLabel: 'Equipamentos',
    kind: 'entity',
    description: 'Parque instalado, status e vínculo com clientes.',
    collection: 'equipamentos',
  },
  {
    id: 'orcamentos',
    label: 'Orçamentos',
    shortLabel: 'Orçamentos',
    kind: 'entity',
    description: 'Propostas comerciais e itens precificados.',
    collection: 'orcamentos',
  },
  {
    id: 'funcionarios',
    label: 'Equipe Técnica',
    shortLabel: 'Equipe',
    kind: 'entity',
    description: 'Cadastro operacional da equipe, especialidades e contatos.',
    collection: 'funcionarios',
  },
  {
    id: 'clientes',
    label: 'Clientes',
    shortLabel: 'Clientes',
    kind: 'entity',
    description: 'Base de atendimento, responsáveis e endereços.',
    collection: 'clientes',
  },
  {
    id: 'contratos',
    label: 'Contratos',
    shortLabel: 'Contratos',
    kind: 'entity',
    description: 'Acordos vigentes, escopo de SLA e receita recorrente.',
    collection: 'contratos',
  },
  {
    id: 'certificados',
    label: 'Certificados',
    shortLabel: 'Certificados',
    kind: 'certificates',
    description: 'Rotinas técnicas, registros emitidos e rastreabilidade.',
    collection: 'certificados',
  },
  {
    id: 'fornecedores',
    label: 'Fornecedores',
    shortLabel: 'Fornecedores',
    kind: 'entity',
    description: 'Rede de compras e apoio técnico.',
    collection: 'fornecedores',
  },
  {
    id: 'pecas',
    label: 'Peças',
    shortLabel: 'Peças',
    kind: 'inventory',
    description: 'Estoque técnico com movimentos e níveis mínimos.',
    collection: 'pecas',
  },
  {
    id: 'acessorios',
    label: 'Acessórios',
    shortLabel: 'Acessórios',
    kind: 'inventory',
    description: 'Itens de apoio usados em campo e em bancada.',
    collection: 'acessorios',
  },
  {
    id: 'padroes-calibracao',
    label: 'Padrões de Calibração',
    shortLabel: 'Padrões',
    kind: 'entity',
    description: 'Ferramentas e padrões rastreáveis para certificação.',
    collection: 'padroesCalibracao',
  },
  {
    id: 'usuarios',
    label: 'Acessos e Perfis',
    shortLabel: 'Acessos',
    kind: 'users',
    description: 'Credenciais, papéis e matriz de permissões.',
    collection: 'users',
  },
  {
    id: 'configuracoes',
    label: 'Configurações',
    shortLabel: 'Configurações',
    kind: 'settings',
    description: 'Identidade neutra do beta, dados da operação e regras.',
    collection: 'configuracoes',
  },
]

const equipmentColumns = [
  { key: 'id', label: 'Código' },
  { key: 'nome', label: 'Equipamento' },
  { key: 'modelo', label: 'Modelo' },
  { key: 'numeroSerie', label: 'Série' },
  { key: 'status', label: 'Status', type: 'status' as const },
]

const inventoryColumns = [
  { key: 'id', label: 'Código' },
  { key: 'nome', label: 'Item' },
  { key: 'quantidade', label: 'Saldo' },
  { key: 'minimo', label: 'Mínimo' },
  { key: 'status', label: 'Status', type: 'status' as const },
]

export const ENTITY_CONFIGS: Record<string, EntityConfig> = {
  clientes: {
    collection: 'clientes',
    moduleId: 'clientes',
    singularLabel: 'cliente',
    pluralLabel: 'clientes',
    description: 'Base de atendimento com dados completos do cliente.',
    prefix: 'CLI',
    searchableKeys: ['id', 'nome', 'documento', 'email', 'telefone', 'cidade'],
    columns: [
      { key: 'id', label: 'Código' },
      { key: 'nome', label: 'Nome' },
      { key: 'documento', label: 'Documento' },
      { key: 'cidade', label: 'Cidade' },
      { key: 'telefone', label: 'Telefone' },
    ],
    fields: [
      { key: 'nome', label: 'Nome do cliente', type: 'text', required: true },
      { key: 'documento', label: 'Documento', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'telefone', label: 'Telefone principal', type: 'phone' },
      { key: 'telefoneSecundario', label: 'Telefone secundário', type: 'phone' },
      { key: 'pessoaContato', label: 'Contato responsável', type: 'text' },
      { key: 'endereco', label: 'Endereço', type: 'text' },
      { key: 'numero', label: 'Número', type: 'text' },
      { key: 'complemento', label: 'Complemento', type: 'text' },
      { key: 'bairro', label: 'Bairro', type: 'text' },
      { key: 'cidade', label: 'Cidade', type: 'text' },
      { key: 'estado', label: 'Estado', type: 'text' },
      { key: 'cep', label: 'CEP', type: 'text' },
      { key: 'observacoes', label: 'Observações', type: 'textarea', multilineRows: 4 },
    ],
  },
  equipamentos: {
    collection: 'equipamentos',
    moduleId: 'equipamentos',
    singularLabel: 'equipamento',
    pluralLabel: 'equipamentos',
    description: 'Cadastro técnico do parque médico.',
    prefix: 'EQ',
    searchableKeys: ['id', 'nome', 'modelo', 'numeroSerie', 'local'],
    columns: equipmentColumns,
    fields: [
      { key: 'nome', label: 'Nome do equipamento', type: 'text', required: true },
      { key: 'modelo', label: 'Modelo', type: 'text', required: true },
      { key: 'numeroSerie', label: 'Número de série', type: 'text', required: true },
      { key: 'tipo', label: 'Tipo', type: 'text' },
      { key: 'clienteId', label: 'Cliente', type: 'relation', relation: { collection: 'clientes', labelKey: 'nome' } },
      { key: 'local', label: 'Local de instalação', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: EQUIPMENT_STATUS_OPTIONS, required: true },
      { key: 'proximaCalibracao', label: 'Próxima calibração', type: 'date' },
    ],
  },
  funcionarios: {
    collection: 'funcionarios',
    moduleId: 'funcionarios',
    singularLabel: 'profissional',
    pluralLabel: 'equipe técnica',
    description: 'Cadastro operacional da equipe técnica.',
    prefix: 'FUNC',
    searchableKeys: ['id', 'nome', 'cargo', 'email', 'especialidade'],
    columns: [
      { key: 'id', label: 'Código' },
      { key: 'nome', label: 'Nome' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'especialidade', label: 'Especialidade' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { key: 'nome', label: 'Nome', type: 'text', required: true },
      { key: 'cargo', label: 'Cargo', type: 'text', required: true },
      { key: 'especialidade', label: 'Especialidade', type: 'text' },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'telefone', label: 'Telefone', type: 'phone' },
      { key: 'ativo', label: 'Ativo', type: 'checkbox' },
    ],
  },
  fornecedores: {
    collection: 'fornecedores',
    moduleId: 'fornecedores',
    singularLabel: 'fornecedor',
    pluralLabel: 'fornecedores',
    description: 'Parceiros comerciais e de suprimento.',
    prefix: 'FOR',
    searchableKeys: ['id', 'nome', 'categoria', 'cnpj', 'email'],
    columns: [
      { key: 'id', label: 'Código' },
      { key: 'nome', label: 'Fornecedor' },
      { key: 'categoria', label: 'Categoria' },
      { key: 'responsavel', label: 'Responsável' },
      { key: 'telefone', label: 'Telefone' },
    ],
    fields: [
      { key: 'nome', label: 'Nome', type: 'text', required: true },
      { key: 'razaoSocial', label: 'Razão social', type: 'text' },
      { key: 'cnpj', label: 'CNPJ', type: 'text' },
      { key: 'categoria', label: 'Categoria', type: 'text' },
      { key: 'responsavel', label: 'Responsável', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'telefone', label: 'Telefone', type: 'phone' },
      { key: 'endereco', label: 'Endereço', type: 'text' },
      { key: 'produtosServicos', label: 'Produtos e serviços', type: 'textarea', multilineRows: 3 },
      { key: 'observacoes', label: 'Observações', type: 'textarea', multilineRows: 4 },
    ],
  },
  pecas: {
    collection: 'pecas',
    moduleId: 'pecas',
    singularLabel: 'peça',
    pluralLabel: 'peças',
    description: 'Estoque técnico com controle por fornecedor e custo.',
    prefix: 'PEC',
    searchableKeys: ['id', 'codigo', 'nome', 'localizacao'],
    columns: inventoryColumns,
    fields: [
      { key: 'codigo', label: 'Código interno', type: 'text', required: true },
      { key: 'nome', label: 'Nome da peça', type: 'text', required: true },
      { key: 'descricao', label: 'Descrição', type: 'textarea', multilineRows: 3 },
      { key: 'fornecedorId', label: 'Fornecedor', type: 'relation', relation: { collection: 'fornecedores', labelKey: 'nome' } },
      { key: 'localizacao', label: 'Localização', type: 'text' },
      { key: 'unidade', label: 'Unidade', type: 'text', required: true },
      { key: 'quantidade', label: 'Quantidade', type: 'number', required: true, min: 0, step: 1 },
      { key: 'minimo', label: 'Estoque mínimo', type: 'number', required: true, min: 0, step: 1 },
      { key: 'precoCusto', label: 'Custo unitário', type: 'currency', min: 0, step: 0.01 },
      { key: 'precoVenda', label: 'Preço de venda', type: 'currency', min: 0, step: 0.01 },
      { key: 'status', label: 'Status', type: 'select', options: INVENTORY_STATUS_OPTIONS, required: true },
    ],
  },
  acessorios: {
    collection: 'acessorios',
    moduleId: 'acessorios',
    singularLabel: 'acessório',
    pluralLabel: 'acessórios',
    description: 'Itens de apoio consumidos em campo e em bancada.',
    prefix: 'ACC',
    searchableKeys: ['id', 'codigo', 'nome', 'localizacao'],
    columns: inventoryColumns,
    fields: [
      { key: 'codigo', label: 'Código interno', type: 'text', required: true },
      { key: 'nome', label: 'Nome do acessório', type: 'text', required: true },
      { key: 'descricao', label: 'Descrição', type: 'textarea', multilineRows: 3 },
      { key: 'fornecedorId', label: 'Fornecedor', type: 'relation', relation: { collection: 'fornecedores', labelKey: 'nome' } },
      { key: 'localizacao', label: 'Localização', type: 'text' },
      { key: 'unidade', label: 'Unidade', type: 'text', required: true },
      { key: 'quantidade', label: 'Quantidade', type: 'number', required: true, min: 0, step: 1 },
      { key: 'minimo', label: 'Estoque mínimo', type: 'number', required: true, min: 0, step: 1 },
      { key: 'precoCusto', label: 'Custo unitário', type: 'currency', min: 0, step: 0.01 },
      { key: 'precoVenda', label: 'Preço de venda', type: 'currency', min: 0, step: 0.01 },
      { key: 'status', label: 'Status', type: 'select', options: INVENTORY_STATUS_OPTIONS, required: true },
    ],
  },
  orcamentos: {
    collection: 'orcamentos',
    moduleId: 'orcamentos',
    singularLabel: 'orçamento',
    pluralLabel: 'orçamentos',
    description: 'Propostas comerciais com itens e desconto.',
    prefix: 'ORC',
    searchableKeys: ['id', 'clienteId', 'status'],
    columns: [
      { key: 'id', label: 'Código' },
      { key: 'clienteId', label: 'Cliente' },
      { key: 'data', label: 'Data', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'total', label: 'Total', type: 'currency' },
    ],
    fields: [
      { key: 'clienteId', label: 'Cliente', type: 'relation', relation: { collection: 'clientes', labelKey: 'nome' }, required: true },
      { key: 'equipamentoId', label: 'Equipamento', type: 'relation', relation: { collection: 'equipamentos', labelKey: 'nome' } },
      { key: 'osId', label: 'OS vinculada', type: 'relation', relation: { collection: 'ordensServico', labelKey: 'id' } },
      { key: 'data', label: 'Data da proposta', type: 'date', required: true },
      { key: 'status', label: 'Status', type: 'select', options: BUDGET_STATUS_OPTIONS, required: true },
      { key: 'prazoExecucao', label: 'Prazo de execução', type: 'text' },
      { key: 'validadeProposta', label: 'Validade', type: 'date' },
      { key: 'desconto', label: 'Desconto', type: 'currency', min: 0, step: 0.01 },
      { key: 'subtotal', label: 'Subtotal', type: 'currency', min: 0, step: 0.01 },
      { key: 'total', label: 'Total', type: 'currency', min: 0, step: 0.01 },
      { key: 'observacoes', label: 'Observações', type: 'textarea', multilineRows: 4 },
    ],
  },
  contratos: {
    collection: 'contratos',
    moduleId: 'contratos',
    singularLabel: 'contrato',
    pluralLabel: 'contratos',
    description: 'Relação contratual com vigência e receita recorrente.',
    prefix: 'CON',
    searchableKeys: ['id', 'clienteId', 'tipo', 'status'],
    columns: [
      { key: 'id', label: 'Código' },
      { key: 'clienteId', label: 'Cliente' },
      { key: 'tipo', label: 'Tipo' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'valorMensal', label: 'Mensal', type: 'currency' },
    ],
    fields: [
      { key: 'clienteId', label: 'Cliente', type: 'relation', relation: { collection: 'clientes', labelKey: 'nome' }, required: true },
      { key: 'tipo', label: 'Tipo de contrato', type: 'select', options: CONTRACT_TYPE_OPTIONS, required: true },
      { key: 'status', label: 'Status', type: 'select', options: CONTRACT_STATUS_OPTIONS, required: true },
      { key: 'inicioVigencia', label: 'Início da vigência', type: 'date', required: true },
      { key: 'fimVigencia', label: 'Fim da vigência', type: 'date', required: true },
      { key: 'valorMensal', label: 'Valor mensal', type: 'currency', min: 0, step: 0.01 },
      { key: 'valorTotal', label: 'Valor total', type: 'currency', min: 0, step: 0.01 },
      { key: 'formaPagamento', label: 'Forma de pagamento', type: 'text' },
      { key: 'sla', label: 'SLA', type: 'text' },
      { key: 'escopo', label: 'Escopo', type: 'textarea', multilineRows: 4 },
      { key: 'responsavelCliente', label: 'Responsável no cliente', type: 'text' },
      { key: 'emailCliente', label: 'Email do cliente', type: 'email' },
      { key: 'telefoneCliente', label: 'Telefone do cliente', type: 'phone' },
      { key: 'observacoes', label: 'Observações', type: 'textarea', multilineRows: 4 },
    ],
  },
  padroesCalibracao: {
    collection: 'padroesCalibracao',
    moduleId: 'padroes-calibracao',
    singularLabel: 'padrão',
    pluralLabel: 'padrões',
    description: 'Instrumentos e padrões usados na certificação técnica.',
    prefix: 'PAD',
    searchableKeys: ['id', 'nome', 'numeroSerie', 'status'],
    columns: [
      { key: 'id', label: 'Código' },
      { key: 'nome', label: 'Padrão' },
      { key: 'numeroSerie', label: 'Série' },
      { key: 'validadeCalibracao', label: 'Validade', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'nome', label: 'Nome do padrão', type: 'text', required: true },
      { key: 'tipo', label: 'Tipo', type: 'text', required: true },
      { key: 'numeroSerie', label: 'Número de série', type: 'text', required: true },
      { key: 'fabricante', label: 'Fabricante', type: 'text' },
      { key: 'dataCalibracao', label: 'Data de calibração', type: 'date', required: true },
      { key: 'validadeCalibracao', label: 'Validade da calibração', type: 'date', required: true },
      { key: 'responsavel', label: 'Responsável', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: CALIBRATION_STATUS_OPTIONS, required: true },
      { key: 'observacoes', label: 'Observações', type: 'textarea', multilineRows: 4 },
    ],
  },
}

export const EQUIPMENT_STATUS_VALUES: EquipmentStatus[] = EQUIPMENT_STATUS_OPTIONS.map((option) => option.value as EquipmentStatus)
export const INVENTORY_STATUS_VALUES: InventoryStatus[] = INVENTORY_STATUS_OPTIONS.map((option) => option.value as InventoryStatus)
export const BUDGET_STATUS_VALUES: BudgetStatus[] = BUDGET_STATUS_OPTIONS.map((option) => option.value as BudgetStatus)
export const CONTRACT_STATUS_VALUES: ContractStatus[] = CONTRACT_STATUS_OPTIONS.map((option) => option.value as ContractStatus)
export const CONTRACT_TYPE_VALUES: ContractType[] = CONTRACT_TYPE_OPTIONS.map((option) => option.value as ContractType)
export const SERVICE_ORDER_STATUS_VALUES: ServiceOrderStatus[] = SERVICE_ORDER_STATUS_OPTIONS.map((option) => option.value as ServiceOrderStatus)
export const CALIBRATION_STATUS_VALUES: CalibrationStatus[] = CALIBRATION_STATUS_OPTIONS.map((option) => option.value as CalibrationStatus)