import { APP_MODULES, DEFAULT_ROLE_ACCESS } from './constants.js'
import type { AppRecordMap, ConfiguracaoSistema, Role, SessionUser } from './types.js'
import { calculateCalibrationStatus } from './utils.js'

const now = '2026-05-20T10:00:00.000Z'

export const demoAccounts: Array<{ email: string; password: string; user: SessionUser }> = [
  {
    email: 'admin@atlasmed.demo',
    password: 'Atlas123!',
    user: {
      id: 'USR-001',
      email: 'admin@atlasmed.demo',
      name: 'Ana Campos',
      role: 'admin',
      staffId: 'FUNC-001',
      mode: 'demo',
    },
  },
  {
    email: 'tecnico@atlasmed.demo',
    password: 'Atlas123!',
    user: {
      id: 'USR-002',
      email: 'tecnico@atlasmed.demo',
      name: 'Rafael Souza',
      role: 'tecnico',
      staffId: 'FUNC-002',
      mode: 'demo',
    },
  },
  {
    email: 'operacao@atlasmed.demo',
    password: 'Atlas123!',
    user: {
      id: 'USR-003',
      email: 'operacao@atlasmed.demo',
      name: 'Marina Lopes',
      role: 'operador',
      staffId: 'FUNC-003',
      mode: 'demo',
    },
  },
]

const configuracoes: ConfiguracaoSistema[] = [
  {
    id: 'company-profile',
    nome: 'Perfil operacional',
    descricao: 'Dados neutros usados no beta e no cabeçalho do painel.',
    valor: {
      nomeEmpresa: 'AtlasMed Beta',
      tagline: 'Gestão moderna para equipamentos médicos e engenharia clínica.',
      cidadeBase: 'Campinas',
      telefone: '(19) 3200-4500',
      email: 'contato@atlasmed.demo',
      endereco: 'Rua das Oficinas, 145',
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'role-access',
    nome: 'Permissões por papel',
    descricao: 'Configuração central dos módulos habilitados por perfil.',
    valor: DEFAULT_ROLE_ACCESS as unknown as Record<string, unknown>,
    createdAt: now,
    updatedAt: now,
  },
]

export const initialDemoDatabase: { [Key in keyof AppRecordMap]: AppRecordMap[Key][] } = {
  clientes: [
    {
      id: 'CLI-001',
      nome: 'Hospital Santa Elisa',
      documento: '12.345.678/0001-90',
      email: 'engenharia@santaelisa.br',
      telefone: '(19) 99888-1000',
      pessoaContato: 'Cláudia Ramos',
      endereco: 'Av. Brasil',
      numero: '1800',
      bairro: 'Centro',
      cidade: 'Campinas',
      estado: 'SP',
      cep: '13015-000',
      observacoes: 'Conta piloto para demonstrações do beta.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'CLI-002',
      nome: 'Clínica Horizonte',
      documento: '45.220.990/0001-10',
      email: 'compras@clinicahorizonte.br',
      telefone: '(11) 95555-8800',
      pessoaContato: 'Igor Menezes',
      endereco: 'Rua Aroeira',
      numero: '88',
      bairro: 'Jardins',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '01420-020',
      createdAt: now,
      updatedAt: now,
    },
  ],
  equipamentos: [
    {
      id: 'EQ-001',
      nome: 'Monitor multiparamétrico',
      fabricante: 'LifeView',
      modelo: 'LifeView M7',
      numeroSerie: 'LV-M7-2401',
      numeroPatrimonio: 'PAT-2024-0145',
      tag: 'TAG-MON-001',
      clienteId: 'CLI-001',
      hospital: 'Hospital Santa Elisa',
      setor: 'UTI Adulto',
      local: 'UTI Adulto — Leito 4',
      tipo: 'Monitorização',
      classeRisco: 'IIb',
      classeEquipamento: 'CF',
      status: 'Em Operação',
      dataAquisicao: '2022-06-15',
      dataInstalacao: '2022-07-01',
      proximaCalibracao: '2026-11-12',
      proximaManutencaoPreventiva: '2026-08-01',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'EQ-002',
      nome: 'Bomba de infusão',
      fabricante: 'FlowCare',
      modelo: 'FlowCare 12',
      numeroSerie: 'FC12-7781',
      numeroPatrimonio: 'PAT-2023-0089',
      tag: 'TAG-BOM-002',
      clienteId: 'CLI-001',
      hospital: 'Hospital Santa Elisa',
      setor: 'Enfermaria',
      local: 'Posto 3 — Sala 12',
      tipo: 'Infusão',
      classeRisco: 'IIb',
      classeEquipamento: 'BF',
      status: 'Em Manutenção',
      dataAquisicao: '2021-03-20',
      dataInstalacao: '2021-04-05',
      proximaCalibracao: '2026-08-18',
      proximaManutencaoPreventiva: '2026-07-15',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'EQ-003',
      nome: 'Desfibrilador externo',
      fabricante: 'ShockLine',
      modelo: 'ShockLine D5',
      numeroSerie: 'D5-3377',
      numeroPatrimonio: 'PAT-2023-0201',
      tag: 'TAG-DEF-003',
      clienteId: 'CLI-002',
      hospital: 'Clínica Horizonte',
      setor: 'Pronto Atendimento',
      local: 'PA — Sala de Emergência',
      tipo: 'Emergência',
      classeRisco: 'III',
      classeEquipamento: 'CF',
      status: 'Em Operação',
      dataAquisicao: '2020-11-10',
      dataInstalacao: '2020-12-01',
      proximaCalibracao: '2026-09-09',
      proximaManutencaoPreventiva: '2026-09-09',
      createdAt: now,
      updatedAt: now,
    },
  ],
  funcionarios: [
    {
      id: 'FUNC-001',
      nome: 'Ana Campos',
      cargo: 'Coordenadora técnica',
      email: 'admin@atlasmed.demo',
      telefone: '(19) 98888-1001',
      contaVinculada: 'USR-001',
      especialidade: 'Gestão técnica',
      ativo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'FUNC-002',
      nome: 'Rafael Souza',
      cargo: 'Técnico biomédico',
      email: 'tecnico@atlasmed.demo',
      telefone: '(19) 98888-1002',
      contaVinculada: 'USR-002',
      especialidade: 'Calibração e bancada',
      ativo: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'FUNC-003',
      nome: 'Marina Lopes',
      cargo: 'Operações',
      email: 'operacao@atlasmed.demo',
      telefone: '(11) 97777-2200',
      contaVinculada: 'USR-003',
      especialidade: 'Backoffice',
      ativo: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  fornecedores: [
    {
      id: 'FOR-001',
      nome: 'BioSupplies',
      razaoSocial: 'BioSupplies Comércio Técnico Ltda',
      cnpj: '21.200.333/0001-55',
      responsavel: 'Maurício Neves',
      email: 'contato@biosupplies.demo',
      telefone: '(11) 3123-9000',
      categoria: 'Peças críticas',
      produtosServicos: 'Sensores, placas e kits de manutenção.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'FOR-002',
      nome: 'TecCabos',
      razaoSocial: 'TecCabos Soluções Hospitalares',
      cnpj: '32.120.444/0001-20',
      responsavel: 'Paula Viana',
      email: 'vendas@teccabos.demo',
      telefone: '(41) 3020-1100',
      categoria: 'Acessórios e cabos',
      productsServicos: 'Cabos, sensores, manguitos e acessórios.',
      createdAt: now,
      updatedAt: now,
    } as unknown as AppRecordMap['fornecedores'],
  ],
  pecas: [
    {
      id: 'PEC-001',
      codigo: 'SENS-778',
      nome: 'Sensor de fluxo',
      descricao: 'Sensor de reposição para bomba de infusão.',
      fornecedorId: 'FOR-001',
      localizacao: 'Estante B2',
      unidade: 'un',
      quantidade: 8,
      minimo: 4,
      precoCusto: 140,
      precoVenda: 230,
      status: 'Ativo',
      historico: [{ data: now, tipo: 'Criação', qtd: 8, saldo: 8, obs: 'Carga inicial do beta' }],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'PEC-002',
      codigo: 'BATT-310',
      nome: 'Bateria standby',
      descricao: 'Bateria para monitores portáteis.',
      fornecedorId: 'FOR-001',
      localizacao: 'Estante A1',
      unidade: 'un',
      quantidade: 2,
      minimo: 3,
      precoCusto: 280,
      precoVenda: 420,
      status: 'Ativo',
      historico: [{ data: now, tipo: 'Criação', qtd: 2, saldo: 2, obs: 'Carga inicial do beta' }],
      createdAt: now,
      updatedAt: now,
    },
  ],
  acessorios: [
    {
      id: 'ACC-001',
      codigo: 'CAB-ECG-5V',
      nome: 'Cabo ECG 5 vias',
      descricao: 'Cabo de monitorização adulto.',
      fornecedorId: 'FOR-002',
      localizacao: 'Gaveta C4',
      unidade: 'un',
      quantidade: 5,
      minimo: 2,
      precoCusto: 78,
      precoVenda: 140,
      status: 'Ativo',
      historico: [{ data: now, tipo: 'Criação', qtd: 5, saldo: 5, obs: 'Carga inicial do beta' }],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ACC-002',
      codigo: 'MANG-NIBP-M',
      nome: 'Manguito NIBP adulto M',
      descricao: 'Manguito para monitor multiparamétrico.',
      fornecedorId: 'FOR-002',
      localizacao: 'Gaveta C2',
      unidade: 'un',
      quantidade: 3,
      minimo: 3,
      precoCusto: 44,
      precoVenda: 88,
      status: 'Ativo',
      historico: [{ data: now, tipo: 'Criação', qtd: 3, saldo: 3, obs: 'Carga inicial do beta' }],
      createdAt: now,
      updatedAt: now,
    },
  ],
  contratos: [
    {
      id: 'CON-001',
      clienteId: 'CLI-001',
      tipo: 'Manutenção',
      status: 'Ativo',
      inicioVigencia: '2026-01-01',
      fimVigencia: '2026-12-31',
      valorMensal: 8200,
      valorTotal: 98400,
      formaPagamento: 'Boleto mensal',
      sla: 'Atendimento em até 24h',
      escopo: 'Manutenção corretiva e preventiva de equipamentos críticos.',
      responsavelCliente: 'Cláudia Ramos',
      emailCliente: 'engenharia@santaelisa.br',
      telefoneCliente: '(19) 99888-1000',
      createdAt: now,
      updatedAt: now,
    },
  ],
  orcamentos: [
    {
      id: 'ORC-001',
      clienteId: 'CLI-002',
      equipamentoId: 'EQ-003',
      data: '2026-05-14',
      status: 'Enviado',
      prazoExecucao: '5 dias úteis',
      validadeProposta: '2026-05-31',
      desconto: 150,
      subtotal: 2450,
      total: 2300,
      observacoes: 'Troca preventiva e calibração completa.',
      itens: [
        { tipo: 'Servico', descricao: 'Calibração e ajustes', quantidade: 1, valorUnitario: 1100 },
        { tipo: 'Peça', descricao: 'Bateria standby', quantidade: 2, valorUnitario: 280, pecaId: 'PEC-002' },
        { tipo: 'Acessório', descricao: 'Cabo ECG 5 vias', quantidade: 2, valorUnitario: 60, acessorioId: 'ACC-001' },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
  ordensServico: [
    {
      id: 'OS-001',
      clienteId: 'CLI-001',
      equipamentoId: 'EQ-002',
      funcionarioId: 'FUNC-002',
      descricao: 'Falha intermitente no fluxo e alarme recorrente.',
      localizacao: 'Posto 3',
      data: '2026-05-18',
      status: 'Em Manutenção',
      prioridade: 'Alta',
      servicosExecutados: 'Diagnóstico inicial e limpeza interna.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'OS-002',
      clienteId: 'CLI-002',
      equipamentoId: 'EQ-003',
      funcionarioId: 'FUNC-001',
      descricao: 'Verificação de descarga rápida da bateria.',
      localizacao: 'Pronto atendimento',
      data: '2026-05-19',
      status: 'Aguardando Peça',
      prioridade: 'Media',
      createdAt: now,
      updatedAt: now,
    },
  ],
  historicoOS: [
    {
      id: 'OS-090',
      clienteId: 'CLI-001',
      equipamentoId: 'EQ-001',
      funcionarioId: 'FUNC-002',
      descricao: 'Calibração anual concluída.',
      localizacao: 'UTI Adulto',
      data: '2026-04-10',
      status: 'Concluída',
      prioridade: 'Baixa',
      servicosExecutados: 'Ajustes finos e certificação.',
      fechadoEm: '2026-04-11T15:00:00.000Z',
      fechamento: {
        funcionarioId: 'FUNC-002',
        acao: 'Calibração e validação final',
        problema: 'Rotina preventiva programada',
        pecasUsadas: [],
        acessoriosUsados: [],
      },
      createdAt: '2026-04-10T08:00:00.000Z',
      updatedAt: '2026-04-11T15:00:00.000Z',
    },
  ],
  certificados: [
    {
      id: 'CERT-001',
      numeroCertificado: 'CAL-2026-001',
      equipamentoId: 'EQ-001',
      equipamentoNome: 'Monitor multiparamétrico',
      equipamentoNumeroSerie: 'LV-M7-2401',
      equipamentoTag: 'TAG-MON-001',
      equipamentoPatrimonio: 'PAT-2024-0145',
      rotinaId: 'ROT-001',
      rotinaNome: 'Inspeção preventiva multiparamétrica',
      padraoId: 'PAD-001',
      padraoNome: 'Analisador Fluke VT650',
      clienteId: 'CLI-001',
      clienteNome: 'Hospital Santa Elisa',
      tecnicoNome: 'Rafael Souza',
      tecnicoRegistro: 'CRBM-SP 12345',
      tipo: 'preventiva',
      data: '2026-04-11',
      proximaData: '2026-10-11',
      statusGeral: 'aprovado',
      conclusaoTecnica: 'Equipamento em perfeito estado de funcionamento. Sem desvios relevantes.',
      recomendacoes: 'Realizar próxima preventiva em 6 meses.',
      observacoes: 'Sem desvios relevantes.',
      checklist: [
        { nome: 'Inspeção visual geral', status: 'ok', medicao: 'Aprovado' },
        { nome: 'Teste de alarmes', status: 'ok', medicao: 'Todos funcionais' },
        { nome: 'Integridade de cabos e acessórios', status: 'ok', medicao: 'Sem avarias' },
        { nome: 'Limpeza interna e externa', status: 'ok' },
        { nome: 'Teste funcional SpO2', status: 'conforme', medicao: '99%' },
        { nome: 'Teste funcional NIBP', status: 'conforme', medicao: 'Dentro do limite' },
        { nome: 'Teste funcional ECG', status: 'conforme', medicao: '12 derivações OK' },
      ],
      condicoesAmbientais: { temperatura: '22°C', umidade: '58%', tensaoRede: '127V' },
      versao: 1,
      assinado: true,
      assinadoPor: 'Rafael Souza',
      assinadoEm: '2026-04-11T16:00:00.000Z',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'CERT-002',
      numeroCertificado: 'CAL-2026-002',
      equipamentoId: 'EQ-002',
      equipamentoNome: 'Bomba de infusão',
      equipamentoNumeroSerie: 'FC12-7781',
      equipamentoTag: 'TAG-BOM-002',
      equipamentoPatrimonio: 'PAT-2023-0089',
      rotinaId: 'ROT-002',
      rotinaNome: 'Calibração de bomba de infusão',
      padraoId: 'PAD-001',
      padraoNome: 'Analisador Fluke VT650',
      clienteId: 'CLI-001',
      clienteNome: 'Hospital Santa Elisa',
      tecnicoNome: 'Rafael Souza',
      tecnicoRegistro: 'CRBM-SP 12345',
      tipo: 'calibracao',
      data: '2026-05-05',
      proximaData: '2027-05-05',
      statusGeral: 'aprovado',
      conclusaoTecnica: 'Bomba calibrada conforme especificação do fabricante. Erro máximo dentro da tolerância.',
      observacoes: 'Todos os pontos de medição dentro da tolerância ±5%.',
      checklist: [
        { nome: 'Inspeção do sensor de fluxo', status: 'ok' },
        { nome: 'Verificação do mecanismo de infusão', status: 'ok' },
        { nome: 'Teste de alarme de oclusão', status: 'ok' },
        { nome: 'Verificação de bateria', status: 'nok', medicao: 'Bateria 72% — recomendado trocar em 6 meses' },
      ],
      medicoes: [
        { pontoNominal: '1 ml/h', valorMedido: '1.02 ml/h', erroEncontrado: '+2%', incerteza: '±0.5%', tolerancia: '±5%', resultado: 'Conforme' },
        { pontoNominal: '10 ml/h', valorMedido: '10.15 ml/h', erroEncontrado: '+1.5%', incerteza: '±0.5%', tolerancia: '±5%', resultado: 'Conforme' },
        { pontoNominal: '100 ml/h', valorMedido: '98.8 ml/h', erroEncontrado: '-1.2%', incerteza: '±0.5%', tolerancia: '±5%', resultado: 'Conforme' },
        { pontoNominal: '500 ml/h', valorMedido: '498 ml/h', erroEncontrado: '-0.4%', incerteza: '±0.5%', tolerancia: '±5%', resultado: 'Conforme' },
      ],
      condicoesAmbientais: { temperatura: '23°C', umidade: '55%', tensaoRede: '127V' },
      versao: 1,
      assinado: true,
      assinadoPor: 'Rafael Souza',
      assinadoEm: '2026-05-05T15:30:00.000Z',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'CERT-003',
      numeroCertificado: 'PAE-2026-001',
      equipamentoId: 'EQ-003',
      equipamentoNome: 'Desfibrilador externo',
      equipamentoNumeroSerie: 'D5-3377',
      equipamentoTag: 'TAG-DEF-003',
      equipamentoPatrimonio: 'PAT-2023-0201',
      clienteId: 'CLI-002',
      clienteNome: 'Clínica Horizonte',
      tecnicoNome: 'Rafael Souza',
      tecnicoRegistro: 'CRBM-SP 12345',
      tipo: 'seguranca-eletrica',
      data: '2026-05-10',
      proximaData: '2027-05-10',
      statusGeral: 'aprovado',
      conclusaoTecnica: 'Equipamento aprovado nos testes de segurança elétrica conforme ABNT NBR IEC 60601-1.',
      observacoes: 'Teste realizado conforme norma vigente. Todos os valores dentro dos limites.',
      checklist: [
        { nome: 'Inspeção visual de cabos e invólucro', status: 'ok' },
        { nome: 'Verificação de aterramento', status: 'conforme' },
        { nome: 'Resistência de isolação', status: 'conforme' },
      ],
      segurancaEletrica: {
        correnteFugaTerra: '0.08 mA',
        correnteFugaInvolucro: '0.05 mA',
        correnteFugaPaciente: '0.008 mA',
        resistenciaTerra: '0.09 Ω',
        tensaoAplicada: '1500 V',
        isolacao: '> 100 MΩ',
        limiteCorrenteFuga: '0.5 mA (terra) / 0.1 mA (paciente CF)',
        limiteResistenciaTerra: '0.2 Ω',
        resultado: 'Aprovado',
      },
      condicoesAmbientais: { temperatura: '21°C', umidade: '52%', tensaoRede: '220V' },
      versao: 1,
      assinado: true,
      assinadoPor: 'Rafael Souza',
      assinadoEm: '2026-05-10T14:00:00.000Z',
      createdAt: now,
      updatedAt: now,
    },
  ],
  rotinasCertificacao: [
    {
      id: 'ROT-001',
      nome: 'Inspeção preventiva multiparamétrica',
      tipo: 'preventiva',
      equipamentoTipo: 'Monitorização',
      descricao: 'Rotina completa de manutenção preventiva para monitores multiparamétricos.',
      criteriosAprovacao: 'Todos os itens do checklist devem estar aprovados. SpO2 e NIBP dentro das especificações.',
      ativo: true,
      campos: [
        { nome: 'Leitura de SpO2', referencia: '98%', unidade: '%' },
        { nome: 'Pressão NIBP', referencia: '120/80', unidade: 'mmHg' },
        { nome: 'Frequência cardíaca', referencia: '80 bpm', unidade: 'bpm' },
      ],
      etapas: [
        {
          id: 'ET-001',
          titulo: 'Inspeção visual',
          descricao: 'Verificar integridade física do equipamento e acessórios.',
          checklist: [
            { item: 'Invólucro sem trincas ou avarias', obrigatorio: true },
            { item: 'Cabos e conectores íntegros', obrigatorio: true },
            { item: 'Display sem pixels mortos', obrigatorio: false },
          ],
          campos: [],
        },
        {
          id: 'ET-002',
          titulo: 'Verificação funcional',
          descricao: 'Testar todas as funções do monitor.',
          checklist: [
            { item: 'Alarmes audiovisuais funcionais', obrigatorio: true },
            { item: 'Todos os parâmetros exibidos corretamente', obrigatorio: true },
          ],
          campos: [
            { nome: 'SpO2 medido', tipo: 'numero', referencia: '98', unidade: '%', tolerancia: '±2%', obrigatorio: true },
            { nome: 'Frequência cardíaca', tipo: 'numero', unidade: 'bpm', obrigatorio: false },
          ],
        },
        {
          id: 'ET-003',
          titulo: 'Limpeza e conservação',
          descricao: 'Limpeza interna e externa conforme protocolo.',
          checklist: [
            { item: 'Limpeza do painel frontal realizada', obrigatorio: true },
            { item: 'Ventiladores e filtros limpos', obrigatorio: true },
          ],
          campos: [],
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ROT-002',
      nome: 'Calibração de bomba de infusão',
      tipo: 'calibracao',
      equipamentoTipo: 'Infusão',
      descricao: 'Calibração e verificação metrológica de bombas de infusão.',
      criteriosAprovacao: 'Erro máximo ±5% em todos os pontos de medição.',
      ativo: true,
      campos: [
        { nome: 'Fluxo 1 ml/h', referencia: '1', unidade: 'ml/h' },
        { nome: 'Fluxo 10 ml/h', referencia: '10', unidade: 'ml/h' },
        { nome: 'Fluxo 100 ml/h', referencia: '100', unidade: 'ml/h' },
        { nome: 'Fluxo 500 ml/h', referencia: '500', unidade: 'ml/h' },
      ],
      etapas: [
        {
          id: 'ET-001',
          titulo: 'Preparação',
          descricao: 'Montar equipamento e padrão de medição.',
          checklist: [
            { item: 'Equipo de infusão instalado corretamente', obrigatorio: true },
            { item: 'Padrão de medição calibrado e dentro da validade', obrigatorio: true },
          ],
          campos: [],
        },
        {
          id: 'ET-002',
          titulo: 'Pontos de medição',
          descricao: 'Realizar medições nos pontos de calibração.',
          checklist: [],
          campos: [
            { nome: '1 ml/h medido', tipo: 'numero', referencia: '1', unidade: 'ml/h', tolerancia: '±5%', obrigatorio: true },
            { nome: '10 ml/h medido', tipo: 'numero', referencia: '10', unidade: 'ml/h', tolerancia: '±5%', obrigatorio: true },
            { nome: '100 ml/h medido', tipo: 'numero', referencia: '100', unidade: 'ml/h', tolerancia: '±5%', obrigatorio: true },
            { nome: '500 ml/h medido', tipo: 'numero', referencia: '500', unidade: 'ml/h', tolerancia: '±5%', obrigatorio: true },
          ],
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'ROT-003',
      nome: 'Teste de segurança elétrica',
      tipo: 'seguranca-eletrica',
      equipamentoTipo: 'Geral',
      descricao: 'Testes de segurança elétrica conforme ABNT NBR IEC 60601-1.',
      criteriosAprovacao: 'Todos os valores abaixo dos limites normativos.',
      ativo: true,
      campos: [
        { nome: 'Corrente de fuga à terra', unidade: 'mA' },
        { nome: 'Corrente de fuga no invólucro', unidade: 'mA' },
        { nome: 'Corrente de fuga no paciente', unidade: 'mA' },
        { nome: 'Resistência de aterramento', unidade: 'Ω' },
      ],
      etapas: [],
      createdAt: now,
      updatedAt: now,
    },
  ],
  padroesCalibracao: [
    {
      id: 'PAD-001',
      nome: 'Analisador Fluke VT650',
      tipo: 'Analisador de gases e ventilação',
      numeroSerie: 'VT650-90011',
      fabricante: 'Fluke Biomedical',
      dataCalibracao: '2026-02-01',
      validadeCalibracao: '2027-02-01',
      responsavel: 'Laboratório parceiro',
      status: calculateCalibrationStatus('2027-02-01'),
      observacoes: 'Padrão principal do laboratório.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  users: demoAccounts.map(({ user }) => ({
    id: user.id,
    email: user.email,
    nome: user.name,
    role: user.role,
    staffId: user.staffId,
    ativo: true,
    createdAt: now,
    updatedAt: now,
  })),
  configuracoes,
}

export const demoRoleAccess = DEFAULT_ROLE_ACCESS

export const demoModuleCatalog = APP_MODULES

export const demoRoles: Role[] = ['admin', 'gerente', 'tecnico', 'operador']